### ISSUE TITLE
cannot import name 'TemporaryDirectory' from 'proto' (unknown location)

### ISSUE THREAD

**Issue by yurivict** [Snaipe/Criterion#467]
Build fails:
```
===>  Building for criterion-2.4.1
[  1% 2/53] /usr/local/bin/msgfmt ../po/fr.po -o po/fr/LC_MESSAGES/criterion.mo
[  3% 3/53] /usr/local/bin/msgfmt ../po/de.po -o po/de/LC_MESSAGES/criterion.mo
[  5% 3/53] /wrkdirs/usr/ports/devel/criterion/work/Criterion-2.4.1/src/protocol/gen-pb.py /usr/local/bin/protoc /usr/local/bin/protoc-gen-nanopb ../src/protocol/criterion.proto ../src/protocol/criterion.options /wrkdirs/usr/ports/devel/criterion/work/Criterion-2.4.1/_build/src
FAILED: src/criterion.pb.c src/criterion.pb.h 
/wrkdirs/usr/ports/devel/criterion/work/Criterion-2.4.1/src/protocol/gen-pb.py /usr/local/bin/protoc /usr/local/bin/protoc-gen-nanopb ../src/protocol/criterion.proto ../src/protocol/criterion.options /wrkdirs/usr/ports/devel/criterion/work/Criterion-2.4.1/_build/src
/usr/local/bin/protoc --plugin=protoc-gen-nanopb=/usr/local/bin/protoc-gen-nanopb -I../src/protocol --nanopb_out=-f ../src/protocol/criterion.options:/wrkdirs/usr/ports/devel/criterion/work/Criterion-2.4.1/_build/src ../src/protocol/criterion.proto
Traceback (most recent call last):
  File "/usr/local/bin/protoc-gen-nanopb", line 7, in <module>
    from nanopb_generator import *
  File "/usr/local/bin/nanopb_generator.py", line 55, in <module>
    from proto import TemporaryDirectory
ImportError: cannot import name 'TemporaryDirectory' from 'proto' (unknown location)
--nanopb_out: protoc-gen-nanopb: Plugin failed with status code 1.
ninja: build stopped: subcommand failed.
===> Compilation failed unexpectedly.
Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
the maintainer.
*** Error code 1
```

Version: 2.4.1
protobuf-3.21.7
clang-14
FreeBSD 13.1

**Comment by paolostivanin** [comment]
this is also the error I get when updating nanopb from 0.4.6 to 0.4.7 :thinking:
